//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KletterDatenbank_MuellerPachler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebiet()
        {
            this.Sektor = new HashSet<Sektor>();
        }
    
        public int ID_Gebiet { get; set; }
        public string NameGebiet { get; set; }
        public string Ort { get; set; }
        public int PLZ { get; set; }
        public string GPS_Parkplatz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sektor> Sektor { get; set; }
    }
}
