//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KletterDatenbank_MuellerPachler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.ZOT_Durchstiegsliste = new HashSet<ZOT_Durchstiegsliste>();
            this.ZOT_Wunschliste = new HashSet<ZOT_Wunschliste>();
        }
    
        public int ID_Route { get; set; }
        public int ID_Sektor { get; set; }
        public string Name { get; set; }
        public string Schwierigkeitsgrad { get; set; }
        public bool IstBoulder { get; set; }
    
        public virtual Sektor Sektor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZOT_Durchstiegsliste> ZOT_Durchstiegsliste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZOT_Wunschliste> ZOT_Wunschliste { get; set; }
    }
}
