//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KletterDatenbank_MuellerPachler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZOT_Durchstiegsliste
    {
        public int ID { get; set; }
        public string Kommentar { get; set; }
        public System.DateTime Durchstiegsdatum { get; set; }
        public int PersonID { get; set; }
        public int RouteID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Route Route { get; set; }
    }
}
