//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KletterDatenbank_MuellerPachler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PACHLERMARTIN\\SQLEXPRESS;Initial Catalog=EF_KletterRouten;Integrated " +
            "Security=True")]
        public string EF_KletterRoutenConnectionString {
            get {
                return ((string)(this["EF_KletterRoutenConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PACHLERMARTIN\\SQLEXPRESS;Initial Catalog=EF_DB_Klettern_MuellerPachle" +
            "r;Integrated Security=True")]
        public string EF_DB_Klettern_MuellerPachlerConnectionString {
            get {
                return ((string)(this["EF_DB_Klettern_MuellerPachlerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PACHLERMARTIN\\SQLEXPRESS;Initial Catalog=EF_DB_Kletterrouten;Integrat" +
            "ed Security=True")]
        public string EF_DB_KletterroutenConnectionString {
            get {
                return ((string)(this["EF_DB_KletterroutenConnectionString"]));
            }
        }
    }
}
